-- Visit 1MY - Canonical categories for Module 1 official scam cases.
-- Existing scam reports and category text are preserved unchanged.

begin;

create table if not exists public.scam_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  display_order integer not null default 100,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint scam_categories_name_check check (trim(name) <> '')
);

insert into public.scam_categories (name, display_order)
values
  ('Currency Exchange Scam', 10),
  ('Taxi Scam', 20),
  ('Pickpocket', 30),
  ('Overcharging', 40),
  ('Photo Scam', 50),
  ('Transport Scam', 60),
  ('QR Code Fraud', 70),
  ('Gift Card Scam', 80),
  ('Fake Services', 90),
  ('Phishing', 100),
  ('Service Complaint', 110),
  ('Other', 120)
on conflict (name) do update set
  display_order = excluded.display_order,
  updated_at = now();

alter table public.scam_categories enable row level security;

drop policy if exists scam_categories_public_read on public.scam_categories;
create policy scam_categories_public_read
  on public.scam_categories
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists scam_categories_admin_manage on public.scam_categories;
create policy scam_categories_admin_manage
  on public.scam_categories
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

revoke all on public.scam_categories from anon, authenticated;
grant select on public.scam_categories to anon, authenticated;
grant insert, update, delete on public.scam_categories to authenticated;
grant usage, select on sequence public.scam_categories_id_seq to authenticated;

commit;
