-- Module 5 professional flows: scenario media and spendable reward XP.
-- Run after 202609090001 and 202609090002.

alter table public.scenarios
  add column if not exists media_type text not null default 'none',
  add column if not exists media_url text,
  add column if not exists media_caption text;

alter table public.scenarios
  drop constraint if exists scenarios_media_type_check;
alter table public.scenarios
  add constraint scenarios_media_type_check
  check (media_type in ('none', 'image', 'video'));

alter table public.scenarios
  drop constraint if exists scenarios_media_url_check;
alter table public.scenarios
  add constraint scenarios_media_url_check
  check (media_type = 'none' or nullif(btrim(media_url), '') is not null);

alter table public.profiles add column if not exists available_xp integer;
update public.profiles
set available_xp = greatest(coalesce(total_xp, 0), 0)
where available_xp is null;
alter table public.profiles alter column available_xp set default 0;
alter table public.profiles alter column available_xp set not null;
alter table public.profiles drop constraint if exists profiles_available_xp_check;
alter table public.profiles add constraint profiles_available_xp_check
  check (available_xp >= 0);

-- Partnership registry: a safety verification record is not sufficient proof
-- that a merchant has authorised Visit 1MY to distribute a commercial offer.
create sequence if not exists public.reward_partner_code_seq start 1;

create table if not exists public.reward_partners (
  id uuid primary key default gen_random_uuid(),
  partner_code text not null default (
    'MCH-' || lpad(nextval('public.reward_partner_code_seq')::text, 6, '0')
  ),
  legal_name text not null,
  display_name text not null,
  registration_number text,
  category text not null default 'Other',
  contact_email text,
  contact_phone text,
  website_url text,
  verification_status text not null default 'pending'
    check (verification_status in ('pending', 'verified', 'rejected', 'suspended')),
  verification_notes text,
  verified_by uuid references public.admin_accounts(id) on delete set null,
  verified_at timestamptz,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists reward_partners_partner_code_key
  on public.reward_partners(partner_code);
create unique index if not exists reward_partners_legal_name_key
  on public.reward_partners(lower(btrim(legal_name)));
create unique index if not exists reward_partners_registration_number_key
  on public.reward_partners(lower(btrim(registration_number)))
  where nullif(btrim(registration_number), '') is not null;

alter table public.reward_vouchers
  add column if not exists partner_id uuid
  references public.reward_partners(id) on delete restrict;

insert into public.reward_partners (
  legal_name, display_name, category, verification_status,
  verification_notes, verified_at
)
select distinct
  btrim(rv.partner_name), btrim(rv.partner_name), 'Legacy sponsor', 'verified',
  'Migrated from an existing published Module 5 reward. Revalidate the commercial agreement.',
  now()
from public.reward_vouchers rv
where nullif(btrim(rv.partner_name), '') is not null
on conflict do nothing;

update public.reward_vouchers rv
set partner_id = rp.id
from public.reward_partners rp
where rv.partner_id is null
  and lower(btrim(rp.legal_name)) = lower(btrim(rv.partner_name));

-- Database-level duplicate protection. UUIDs remain internal identifiers;
-- human-readable codes continue to be generated by the earlier migration.
create unique index if not exists learning_lessons_unique_title_key
  on public.learning_lessons(lower(btrim(title)));
create unique index if not exists quiz_questions_unique_question_key
  on public.quiz_questions(lower(btrim(question)));
create unique index if not exists scenarios_unique_title_key
  on public.scenarios(lower(btrim(title)));

create or replace function public.enforce_reward_partner_policy()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  partner_ok boolean;
begin
  select rp.is_active and rp.verification_status = 'verified'
  into partner_ok
  from public.reward_partners rp
  where rp.id = new.partner_id;

  if (new.status = 'published' or coalesce(new.is_active, false))
     and coalesce(partner_ok, false) is not true then
    raise exception 'Only an active, verified reward partner can sponsor a voucher';
  end if;

  select rp.display_name into new.partner_name
  from public.reward_partners rp
  where rp.id = new.partner_id;
  return new;
end;
$$;

drop trigger if exists reward_voucher_partner_policy
  on public.reward_vouchers;
create trigger reward_voucher_partner_policy
before insert or update of partner_id, status, is_active
on public.reward_vouchers
for each row execute function public.enforce_reward_partner_policy();

create or replace function public.stamp_reward_partner_verification()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' and new.verification_status = 'verified' then
    new.verified_by := auth.uid();
    new.verified_at := now();
  elsif tg_op = 'UPDATE'
        and new.verification_status = 'verified'
        and old.verification_status is distinct from 'verified' then
    new.verified_by := auth.uid();
    new.verified_at := now();
  elsif new.verification_status <> 'verified' then
    new.verified_by := null;
    new.verified_at := null;
  end if;
  return new;
end;
$$;

drop trigger if exists reward_partner_verification_stamp
  on public.reward_partners;
create trigger reward_partner_verification_stamp
before insert or update of verification_status on public.reward_partners
for each row execute function public.stamp_reward_partner_verification();

create or replace function public.archive_unverified_partner_vouchers()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.is_active is not true or new.verification_status <> 'verified' then
    update public.reward_vouchers
    set status = 'archived', is_active = false, updated_at = now()
    where partner_id = new.id and (status <> 'archived' or is_active = true);
  end if;
  return new;
end;
$$;

drop trigger if exists reward_partner_voucher_archive
  on public.reward_partners;
create trigger reward_partner_voucher_archive
after update of verification_status, is_active on public.reward_partners
for each row execute function public.archive_unverified_partner_vouchers();

alter table public.reward_partners enable row level security;
drop policy if exists "reward partners admin read" on public.reward_partners;
create policy "reward partners admin read" on public.reward_partners
  for select to authenticated using (public.is_awareness_admin());
drop policy if exists "reward partners admin write" on public.reward_partners;
create policy "reward partners admin write" on public.reward_partners
  for all to authenticated
  using (public.is_awareness_admin()) with check (public.is_awareness_admin());

create or replace function public.award_learning_xp(xp_amount integer)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or xp_amount <= 0 or xp_amount > 500 then
    raise exception 'Invalid XP award';
  end if;

  update public.profiles
  set total_xp = coalesce(total_xp, 0) + xp_amount,
      available_xp = coalesce(available_xp, 0) + xp_amount,
      current_level = floor((coalesce(total_xp, 0) + xp_amount) / 200.0)::integer + 1,
      updated_at = now()
  where id = auth.uid();
end;
$$;

create or replace function public.admin_save_awareness_scenario(
  scenario_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  target_id uuid;
  target_step_id uuid;
  option_value text;
  option_index integer := 0;
  correct_index integer := coalesce((scenario_payload->>'correct_index')::integer, 0);
  target_media_type text := coalesce(nullif(scenario_payload->>'media_type', ''), 'none');
begin
  if not public.is_awareness_admin() then
    raise exception 'Administrator access required';
  end if;
  if target_media_type not in ('none', 'image', 'video') then
    raise exception 'Unsupported scenario media type';
  end if;
  if target_media_type <> 'none'
     and nullif(btrim(scenario_payload->>'media_url'), '') is null then
    raise exception 'A public media URL is required';
  end if;

  target_id := nullif(scenario_payload->>'id', '')::uuid;
  if target_id is null then
    insert into public.scenarios (
      title, description, category, difficulty, xp_reward, status,
      is_active, published_at, updated_at,
      media_type, media_url, media_caption
    ) values (
      scenario_payload->>'title', scenario_payload->>'description',
      coalesce(scenario_payload->>'category', 'General'),
      coalesce(scenario_payload->>'difficulty', 'Beginner'),
      coalesce((scenario_payload->>'xp_reward')::integer, 50),
      coalesce(scenario_payload->>'status', 'draft'),
      coalesce(scenario_payload->>'status', 'draft') = 'published',
      case when scenario_payload->>'status' = 'published' then now() end,
      now(), target_media_type,
      nullif(btrim(scenario_payload->>'media_url'), ''),
      nullif(btrim(scenario_payload->>'media_caption'), '')
    ) returning id into target_id;
  else
    update public.scenarios
    set title = scenario_payload->>'title',
        description = scenario_payload->>'description',
        category = coalesce(scenario_payload->>'category', 'General'),
        difficulty = coalesce(scenario_payload->>'difficulty', 'Beginner'),
        xp_reward = coalesce((scenario_payload->>'xp_reward')::integer, 50),
        status = coalesce(scenario_payload->>'status', 'draft'),
        is_active = coalesce(scenario_payload->>'status', 'draft') = 'published',
        published_at = case
          when scenario_payload->>'status' = 'published' then coalesce(published_at, now())
          else published_at
        end,
        updated_at = now(),
        media_type = target_media_type,
        media_url = nullif(btrim(scenario_payload->>'media_url'), ''),
        media_caption = nullif(btrim(scenario_payload->>'media_caption'), '')
    where id = target_id;
  end if;

  delete from public.scenario_options
  where step_id in (
    select id from public.scenario_steps where scenario_id = target_id
  );
  delete from public.scenario_steps where scenario_id = target_id;

  insert into public.scenario_steps (scenario_id, situation, step_order)
  values (target_id, scenario_payload->>'situation', 1)
  returning id into target_step_id;

  for option_value in
    select jsonb_array_elements_text(scenario_payload->'options')
  loop
    insert into public.scenario_options (
      step_id, option_text, is_correct, feedback
    ) values (
      target_step_id, option_value, option_index = correct_index,
      coalesce(scenario_payload->>'feedback', '')
    );
    option_index := option_index + 1;
  end loop;

  return target_id;
end;
$$;

create or replace function public.claim_reward_voucher(target_voucher_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  selected_code public.voucher_codes%rowtype;
  existing_code text;
  reward_cost integer;
  xp_balance integer;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  select ucv.full_promo_code into existing_code
  from public.user_claimed_vouchers ucv
  where ucv.user_id = auth.uid() and ucv.voucher_id = target_voucher_id;
  if existing_code is not null then
    return existing_code;
  end if;

  select rv.required_xp into reward_cost
  from public.reward_vouchers rv
  where rv.id = target_voucher_id
    and rv.status = 'published'
    and rv.is_active = true
    and rv.valid_until > now()
  for update;
  if reward_cost is null then
    raise exception 'This reward is no longer available';
  end if;

  select p.available_xp into xp_balance
  from public.profiles p
  where p.id = auth.uid()
  for update;
  if xp_balance is null then
    raise exception 'Learning profile not found';
  end if;
  if xp_balance < reward_cost then
    raise exception 'Not enough XP to redeem this reward';
  end if;

  select * into selected_code
  from public.voucher_codes
  where voucher_id = target_voucher_id and status = 'available'
  order by created_at
  for update skip locked
  limit 1;
  if selected_code.id is null then
    raise exception 'This reward is currently out of stock';
  end if;

  update public.profiles
  set available_xp = available_xp - reward_cost,
      updated_at = now()
  where id = auth.uid();

  update public.voucher_codes
  set status = 'claimed', claimed_by = auth.uid(), claimed_at = now()
  where id = selected_code.id;

  insert into public.user_claimed_vouchers (
    user_id, voucher_id, voucher_code_id, full_promo_code
  ) values (
    auth.uid(), target_voucher_id, selected_code.id, selected_code.code
  );

  return selected_code.code;
end;
$$;

revoke all on function public.award_learning_xp(integer)
  from public, anon, authenticated;
grant execute on function public.admin_save_awareness_scenario(jsonb)
  to authenticated;
grant execute on function public.claim_reward_voucher(uuid)
  to authenticated;
